CREATE TABLE warehouse(
                          warehouse_id BIGINT PRIMARY KEY,
                          location VARCHAR(255) NOT NULL,
                          capacity INT NOT NULL,
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE item (
                      item_id BIGINT PRIMARY KEY,
                      item_name VARCHAR(255) NOT NULL,
                      warehouse_id BIGINT NOT NULL,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      CONSTRAINT fk_item_warehouse
                          FOREIGN KEY (warehouse_id)
                              REFERENCES warehouse(warehouse_id)
                              ON DELETE CASCADE
);

CREATE TABLE sensor (
                        sensor_id BIGINT PRIMARY KEY,
                        warehouse_id BIGINT NOT NULL,
                        status VARCHAR(50) NOT NULL,
                        last_active_at TIMESTAMP,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_sensor_warehouse
                            FOREIGN KEY (warehouse_id)
                                REFERENCES warehouse(warehouse_id)
                                ON DELETE CASCADE
);

CREATE TABLE sensor_reading (
                                reading_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                sensor_id BIGINT NOT NULL,
                                latitude DOUBLE,
                                longitude DOUBLE,
                                humidity DOUBLE,
                                tamper_detected BOOLEAN,
                                recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                CONSTRAINT fk_reading_sensor
                                    FOREIGN KEY (sensor_id)
                                        REFERENCES sensor(sensor_id)
                                        ON DELETE CASCADE
);

CREATE TABLE sensor_configuration (
                                      sensor_id BIGINT PRIMARY KEY,
                                      humidity_threshold DOUBLE NOT NULL,
                                      tamper_monitoring_enabled BOOLEAN NOT NULL,
                                      reporting_interval_seconds INT NOT NULL,
                                      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                      CONSTRAINT fk_configuration_sensor
                                          FOREIGN KEY (sensor_id)
                                              REFERENCES sensor(sensor_id)
                                              ON DELETE CASCADE
);

CREATE TABLE alert (
                       alert_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       sensor_id BIGINT NOT NULL,
                       reading_id BIGINT,
                       alert_type VARCHAR(100) NOT NULL,
                       message VARCHAR(500) NOT NULL,
                       severity VARCHAR(50) NOT NULL,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       CONSTRAINT fk_alert_sensor
                           FOREIGN KEY (sensor_id)
                               REFERENCES sensor(sensor_id)
                               ON DELETE CASCADE,
                       CONSTRAINT fk_alert_reading
                           FOREIGN KEY (reading_id)
                               REFERENCES sensor_reading(reading_id)
                               ON DELETE SET NULL
);
