package com.logitrack;

import com.logitrack.db.ConnectionProvider;
import com.logitrack.db.DataSourceConnectionProvider;
import com.logitrack.db.JdbcTemplate;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;

import javax.sql.DataSource;

public abstract class BaseTest {

    protected JdbcTemplate jdbcTemplate;
    protected DataSource dataSource;

    @BeforeEach
    void setUpDatabase() {
        JdbcDataSource jdbcDataSource = new JdbcDataSource();
        jdbcDataSource.setURL("jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL");
        jdbcDataSource.setUser("sa");
        jdbcDataSource.setPassword("");

        this.dataSource = jdbcDataSource;

        ConnectionProvider connectionProvider = new DataSourceConnectionProvider(dataSource);
        this.jdbcTemplate = new JdbcTemplate(connectionProvider);

        recreateSchema();
    }

    protected void recreateSchema() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS alert");
        jdbcTemplate.execute("DROP TABLE IF EXISTS sensor_reading");
        jdbcTemplate.execute("DROP TABLE IF EXISTS sensor_configuration");
        jdbcTemplate.execute("DROP TABLE IF EXISTS sensor");
        jdbcTemplate.execute("DROP TABLE IF EXISTS item");
        jdbcTemplate.execute("DROP TABLE IF EXISTS warehouse");

        jdbcTemplate.execute("""
                CREATE TABLE warehouse(
                    warehouse_id BIGINT PRIMARY KEY,
                    location VARCHAR(255) NOT NULL,
                    capacity INT NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE sensor (
                    sensor_id BIGINT PRIMARY KEY,
                    warehouse_id BIGINT NOT NULL,
                    status VARCHAR(50) NOT NULL,
                    last_active_at TIMESTAMP,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_sensor_warehouse
                        FOREIGN KEY (warehouse_id)
                        REFERENCES warehouse(warehouse_id)
                        ON DELETE CASCADE
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE sensor_configuration (
                    sensor_id BIGINT PRIMARY KEY,
                    humidity_threshold DOUBLE PRECISION,
                    tamper_monitoring_enabled BOOLEAN,
                    reporting_interval_seconds INT,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_config_sensor
                        FOREIGN KEY (sensor_id)
                        REFERENCES sensor(sensor_id)
                        ON DELETE CASCADE
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE sensor_reading (
                    reading_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    sensor_id BIGINT NOT NULL,
                    latitude DOUBLE PRECISION,
                    longitude DOUBLE PRECISION,
                    humidity DOUBLE PRECISION,
                    tamper_detected BOOLEAN,
                    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_reading_sensor
                        FOREIGN KEY (sensor_id)
                        REFERENCES sensor(sensor_id)
                        ON DELETE CASCADE
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE item (
                    item_id BIGINT PRIMARY KEY,
                    item_name VARCHAR(255) NOT NULL,
                    warehouse_id BIGINT NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_item_warehouse
                        FOREIGN KEY (warehouse_id)
                        REFERENCES warehouse(warehouse_id)
                        ON DELETE CASCADE
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE alert (
                    alert_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    sensor_id BIGINT NOT NULL,
                    reading_id BIGINT,
                    alert_type VARCHAR(100),
                    message VARCHAR(1000),
                    severity VARCHAR(50),
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_alert_sensor
                        FOREIGN KEY (sensor_id)
                        REFERENCES sensor(sensor_id)
                        ON DELETE CASCADE,
                    CONSTRAINT fk_alert_reading
                        FOREIGN KEY (reading_id)
                        REFERENCES sensor_reading(reading_id)
                        ON DELETE SET NULL
                )
                """);

        jdbcTemplate.execute("""
                INSERT INTO warehouse (warehouse_id, location, capacity, created_at)
                VALUES (1, 'Hyderabad Warehouse', 500, CURRENT_TIMESTAMP)
                """);

        jdbcTemplate.execute("""
                INSERT INTO warehouse (warehouse_id, location, capacity, created_at)
                VALUES (2, 'Bengaluru Warehouse', 350, CURRENT_TIMESTAMP)
                """);

        jdbcTemplate.execute("""
                INSERT INTO sensor (sensor_id, warehouse_id, status, last_active_at, created_at)
                VALUES (101, 1, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """);

        jdbcTemplate.execute("""
                INSERT INTO sensor (sensor_id, warehouse_id, status, last_active_at, created_at)
                VALUES (102, 1, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """);

        jdbcTemplate.execute("""
                INSERT INTO sensor (sensor_id, warehouse_id, status, last_active_at, created_at)
                VALUES (103, 2, 'INACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """);
    }
}
